// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: url_queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUrl = `-- name: CreateUrl :one
insert into urls (id, url, lastCrawledAt) values ($1, $2, $3) returning id, url, lastcrawledat
`

type CreateUrlParams struct {
	ID            uuid.UUID
	Url           string
	Lastcrawledat int64
}

func (q *Queries) CreateUrl(ctx context.Context, arg CreateUrlParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createUrl, arg.ID, arg.Url, arg.Lastcrawledat)
	var i Url
	err := row.Scan(&i.ID, &i.Url, &i.Lastcrawledat)
	return i, err
}

const getUrlByUrl = `-- name: GetUrlByUrl :one
select id, url, lastcrawledat from urls where url=$1
`

func (q *Queries) GetUrlByUrl(ctx context.Context, url string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getUrlByUrl, url)
	var i Url
	err := row.Scan(&i.ID, &i.Url, &i.Lastcrawledat)
	return i, err
}
