// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type CrawlTimestamp struct {
	Crawledat int64
	Indexed   sql.NullBool
	SecureUrl string
}

type Url struct {
	ID            uuid.UUID
	Url           string
	Lastcrawledat int64
}
